import Head from 'next/head'
import { serverSideTranslations } from '@core/i18n/serverSideTranslations'
import { RootLayout } from '@core/common/layouts/RootLayout/RootLayout'
import { HomeScreen } from '@domains/home/HomeScreen'
import { homeNamespaces } from '@domains/home/homeNamespaces'
import { getResidentArtists } from '@core/artist/data/ArtistRepository'
import type { GetServerSideProps } from '@lib/next/getServerSideProps'
import type { Artist } from '@core/artist/data/ArtistModel'
import { getUpcomingEvents } from '@core/event/data/EventRepository'
import type { Event } from '@core/event/data/EventModel'
import type { Staff } from '@core/staff/data/StaffModel'
import { getStaff } from '@core/staff/data/StaffRepository'
import { HomeContent, getHomeContent } from '@domains/home/data'

export const getServerSideProps: GetServerSideProps = async () => {
  const artists = await getResidentArtists()
  const events = await getUpcomingEvents()
  const staff = await getStaff()
  const homeContent = await getHomeContent()
  return {
    props: {
      artists,
      events,
      staff,
      homeContent,
      ...(await serverSideTranslations(homeNamespaces)),
    },
  }
}

type HomeProps = {
  artists?: Artist[]
  events?: Event[]
  staff?: Staff[]
  homeContent?: HomeContent
}

export default function Home({ artists, events, staff, homeContent }: HomeProps) {
  return (
    <RootLayout className={'overflow-x-hidden'}>
      <Head>
        <title>Pygments Records</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:title" content="Pygments Records" />
        <meta property="og:description" content="Pygments explore les dimensions de la musique électronique" />
        <meta property="og:image" content="https://drive.google.com/file/d/1V2lN-NG2pTCGH160UwiYQMJR_sJOMPgU/view?usp=sharing" />
        <meta name="twitter:card" content="summary_large_image"/>
        <meta name="twitter:title" content="Pygments Records"/>
        <meta name="twitter:description" content="Pygments explore les dimensions de la musique électronique"/>
        <meta name="twitter:image" content="https://drive.google.com/file/d/1V2lN-NG2pTCGH160UwiYQMJR_sJOMPgU/view?usp=sharing"/>
        <link rel="icon" href="/Format Facebook.png" />
      </Head>
      <HomeScreen
        content={homeContent}
        artists={artists ?? []}
        events={events ?? []}
        staff={staff ?? []}
      />
    </RootLayout>
  )
}
