import Head from "next/head";
import { serverSideTranslations } from "@core/i18n/serverSideTranslations";
import { RootLayout } from "@core/common/layouts/RootLayout/RootLayout";
import { HomeScreen } from "@domains/home/HomeScreen";
import { homeNamespaces } from "@domains/home/homeNamespaces";
import { getResidentArtists } from "@core/artist/data/ArtistRepository";
import type { GetServerSideProps } from "@lib/next/getServerSideProps";
import type { Artist } from "@core/artist/data/ArtistModel";
import { getUpcomingEvents } from "@core/event/data/EventRepository";
import type { Event } from "@core/event/data/EventModel";
import type {Staff} from "@core/staff/data/StaffModel";
import {getStaff} from "@core/staff/data/StaffRepository";

export const getServerSideProps: GetServerSideProps = async ({ locale, defaultLocale }) => {
  const artists = await getResidentArtists();
  const events = await getUpcomingEvents();
  const staff = await getStaff()
  return {
    props: {
      artists,
      events,
      staff,
      ...(await serverSideTranslations(locale ?? defaultLocale, homeNamespaces)),
    },
  };
};

type HomeProps = {
  artists?: Artist[];
  events?: Event[];
  staff?: Staff[];
};

export default function Home({ artists, events, staff}: HomeProps) {
  return (
    <RootLayout className={"overflow-x-hidden"}>
      <Head>
        <title>Pygments Records</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Format Facebook.png" />
      </Head>
      <HomeScreen artists={artists ?? []} events={events ?? []} staff={staff ?? []} />
    </RootLayout>
  );
}
