import Head from "next/head";
import type { GetStaticProps } from "@lib/next/getStaticProps";
import { serverSideTranslations } from "@core/i18n/serverSideTranslations";
import { RootLayout } from "@core/common/layouts/RootLayout/RootLayout";
import { TimelineScreen } from "@domains/timeline/TimelineScreen";
import { timelineNamespaces } from "@domains/timeline/timelineNamespaces";
import { getEvents } from "@core/event/data/EventRepository";
import type { Event } from "@core/event/data/EventModel";

export const getStaticProps: GetStaticProps<TimelineProps> = async ({ locale, defaultLocale }) => {
  const events = await getEvents();
  return {
    props: {
      events,
      ...(await serverSideTranslations(locale ?? defaultLocale, timelineNamespaces)),
    },
    revalidate: 60, // 1 minute,
  };
};

type TimelineProps = {
  events?: Event[];
};

export default function Timeline({ events }: TimelineProps) {
  if (events === undefined) {
    return <p>loading...</p>;
  }
  return (
    <RootLayout>
      <Head>
        <title>Timeline</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Format Facebook.png" />
      </Head>
      <TimelineScreen events={events} />
    </RootLayout>
  );
}
