import Head from "next/head";
import type { GetStaticProps } from "@lib/next/getStaticProps";
import { serverSideTranslations } from "@core/i18n/serverSideTranslations";
import { RootLayout } from "@core/common/layouts/RootLayout/RootLayout";
import { TimelineScreen } from "@domains/timeline/TimelineScreen";
import { timelineNamespaces } from "@domains/timeline/timelineNamespaces";

export const getStaticProps: GetStaticProps = async ({ locale, defaultLocale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? defaultLocale, timelineNamespaces)),
    },
  };
};

export default function Timeline() {
  return (
    <RootLayout>
      <Head>
        <title>Timeline</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Format Facebook.png" />
      </Head>
      <TimelineScreen />
    </RootLayout>
  );
}
