// Autogenerated by typings-for-css-modules-loader.
// Please do not modify this file !

declare namespace RootLayoutModuleCssNamespace {
  export interface IRootLayoutModuleCss {
    container: string;
  }
}

declare const RootLayoutModuleCssModule: RootLayoutModuleCssNamespace.IRootLayoutModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: RootLayoutModuleCssNamespace.IRootLayoutModuleCss;
};

export = RootLayoutModuleCssModule;
