const path = require("path");
const webpack = require("webpack");
const { PHASE_DEVELOPMENT_SERVER } = require("next/dist/next-server/lib/constants");
const loadConfig = require("next/dist/next-server/server/config").default;
const { getPostCssPlugins } = require("next/dist/build/webpack/config/blocks/css/plugins");
const { getCssModuleLoader } = require("next/dist/build/webpack/config/blocks/css/loaders");
const { logger } = require("@storybook/node-logger");

const CWD = process.cwd();

const cssModuleRegEx = /\.module\.css$/;

async function webpackFinal(webpackConfig) {
  const cssRule = webpackConfig.module.rules.find((_) => _.test.test("hello.css"));

  const isProduction = false;
  const nextConfig = loadConfig(PHASE_DEVELOPMENT_SERVER, CWD);

  const postCssPlugins = await getPostCssPlugins(CWD, isProduction, true);
  const nextCssModuleRule = {
    test: cssModuleRegEx,
    sideEffects: false,
    issuer: { and: [CWD], not: [/node_modules/] },
    use: getCssModuleLoader(
      {
        rootDirectory: CWD,
        customAppFile: null,
        isDevelopment: !isProduction,
        isProduction,
        isClient: true,
        isServer: false,
        assetPrefix: nextConfig.assetPrefix
          ? nextConfig.assetPrefix.endsWith("/")
            ? nextConfig.assetPrefix.slice(0, -1)
            : nextConfig.assetPrefix
          : "",
        sassOptions: nextConfig.sassOptions,
        productionBrowserSourceMaps: false,
      },
      postCssPlugins
    ),
  };

  if (!cssRule || !nextCssModuleRule) {
    logger.warn("=> Next.js preset could not be applied. Skipping");
    return webpackConfig;
  } else {
    const useEntries = cssRule.use.map((entry) => {
      if (entry && entry.loader && entry.loader.match(/\/css-loader/g)) {
        return nextCssModuleRule.use[1];
      } else {
        return entry;
      }
    });
    useEntries.splice(1, 0, {
      loader: require.resolve("@teamsupercell/typings-for-css-modules-loader"),
      options: {
        banner:
          "// Autogenerated by typings-for-css-modules-loader.\n// Please do not modify this file !\n",
        verifyOnly: process.env.NODE_ENV === "production",
      },
    });
    const moduleRule = {
      ...nextCssModuleRule,
      use: useEntries,
    };

    logger.info("=> Using next.js preset");
    return {
      ...webpackConfig,
      module: {
        ...(webpackConfig?.module || {}),
        rules: [
          moduleRule,
          ...webpackConfig.module.rules.map((_) => {
            if (_ && _.test instanceof RegExp && _.test.test("hello.css")) {
              return {
                ..._,
                exclude: cssModuleRegEx,
              };
            } else {
              return _;
            }
          }),
        ],
      },
      plugins: [new webpack.WatchIgnorePlugin([/css\.d\.ts$/]), ...webpackConfig.plugins],
    };
  }
}

module.exports = {
  webpackFinal,
};
