// Autogenerated by typings-for-css-modules-loader.
// Please do not modify this file !

declare namespace HomeScreenModuleCssNamespace {
  export interface IHomeScreenModuleCss {
    card: string;
    code: string;
    description: string;
    grid: string;
    title: string;
  }
}

declare const HomeScreenModuleCssModule: HomeScreenModuleCssNamespace.IHomeScreenModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: HomeScreenModuleCssNamespace.IHomeScreenModuleCss;
};

export = HomeScreenModuleCssModule;
